import "@/styles/globals.scss"
import { Roboto } from "next/font/google"

const roboto = Roboto({
  subsets: ["latin"], // Correct subset
  weight: ["400", "700"], // Specify the weights you want to use
})

export const metadata = {
  title: "CLINAN",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main>{children}</main>
      </body>
    </html>
  )
}
